# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envgroups', '0015_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='dose',
            new_name='Acupuncture',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='three',
            new_name='Animal_Husbandry',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tools',
            new_name='Aquaponics_Hydroponics',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tres',
            new_name='Art_Supplies',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='two',
            new_name='Audio_Video_Engineering',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='uno',
            new_name='Automotive_Maintenance',
        ),
        migrations.AddField(
            model_name='project',
            name='Bodywork_Breathwork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Children_Programs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Community_Space',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Compost_Manure_Mulch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Composting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Construction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Construction_Materials_Electrical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Construction_Materials_Finishing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Construction_Materials_Plumbing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Construction_Materials_Structural',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Cooking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Dance_Performance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Digital_Media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Disruptive_Action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Domestic_Animals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Earthmoving_Equipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Energy_Generation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Energy_Installation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Facilitation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Gardening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Grant_Writing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Green_Building',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Herbal_Medicine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Journalism',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Land_Agriculture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Land_Housing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Legal_Defense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Legal_Regulations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Lights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Local_Community_Knowledge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Local_Ecology_Knowledge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Manual_Labor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Money',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Music',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Painting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Photography',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Planning_Coordination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Plant_Starts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Pots',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Promoting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Sculpture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Seeds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Site_Planning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Sound_Healing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Teaching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Tools_Art',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Tools_Construction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Tools_Farming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='Web_Development',
            field=models.BooleanField(default=False),
        ),
    ]
